[package]
name = "rust_doc_markdown"
version = "0.1.0"
authors = ["Maren Afflerbach <maren@afflerbach.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
